import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "react-datepicker/dist/react-datepicker.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AdWorld",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<head>
  <meta charSet="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
  <link
    href="https://fonts.googleapis.com/css2?family=Bangers&family=Dancing+Script:wght@400..700&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
    rel="stylesheet"
  />

  <link rel="icon" href="/img/logo/logo_adworld.png" sizes="any" />
  <link rel="icon" type="image/png" href="/img/favicon.png" />
  <link rel="apple-touch-icon" href="/img/apple-icon.png" />
  <link rel="manifest" href="/manifest.json" />
</head>

<body
  className={`${geistSans.variable} ${geistMono.variable} antialiased`}
>
  {children}
     <Toaster position="top-right" />
</body>
    </html>
  );
}
